- .coveragerc
- identify/identify.py
- tests/identify_test.py
This is almost an exact copy-paste from pre-commit:
https://github.com/pre-commit/pre-commit/blob/master/pre_commit/util.py
It kinda sucks that it's `identify.identify`. All of the code could fit in one module, but we're probably going to want the mappings from extension to tags and interpreter to tags to go in separate modules, so I made this a package.
Should I move this code to `identify/__init__.py` so you can still `import identify` instead of `from identify import identify`? That seems kinda sneaky.
> Add shebang parsing

- identify/identify.py
- tests/identify_test.py
Add implementations of `tags_from_path` (based on the description in the README) and `is_text`.
The main things left before this library is usable are implementing `tags_from_filename` and `tags_from_interpreter` (right now they only understand python).
> Add implementation of tags_from_path, is_text

- identify/extensions.py
For python wsgi applications it's relatively common to list your entrypoint in a `.wsgi` file
> Add .wsgi extension

- identify/extensions.py
Refer-to: Configuration — yamllint 1.11.1 documentation <https://yamllint.readthedocs.io/en/stable/configuration.html>
Signed-off-by: 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>
> Add yamllint configuration to extensions

- identify/extensions.py
Intentionally excluded C because CUDA C has some additional syntax.
> Add .cu extension for cuda

- identify/extensions.py
Ansible uses .j2 as the de-facto extension for Jinja templates.  This change identifies .j2 files as jinja.
> Identify .j2 extension as jinja2

- identify/extensions.py
- identify/identify.py
- tests/extensions_test.py
- tests/identify_test.py
See https://github.com/pre-commit/pre-commit-hooks/issues/346#issuecomment-455670562
> plist can be either binary or text

- identify/extensions.py
Currently, CMakeLists.txt files are identified as plain text files because of their .txt extension.
Instead they should be tagged with `cmake`.
> Identify CMakeLists.txt as cmake file

- identify/identify.py
- tests/identify_test.py
One of the tests in valgrind specifically provides a shebang that is
malformed (contains just a `#!`), which is technically valid bourne
shell syntax.
Fix the code to check that the result from `shlex.split(..)` isn't an
empty `tuple` to avoid an `IndexError` traceback when malformed input
is provided to `identify`.
Add a testcase for the issue.
> Handle malformed shebangs

- identify/extensions.py
The list of conventional AsciiDoc extensions is found here:
https://asciidoctor.org/docs/asciidoc-recommended-practices/#document-extension
Although GitHub supports a file extension of `.asc`, the reference above advises against using it due to collisions with other file types:
> We strongly recommend against using the .asc extension. The connection to AsciiDoc isn’t immediately obvious and it gets falsely identified as a PGP file on Linux.
> feat: add adoc/asciidoc file extension

- identify/extensions.py
.ml / .mli is the OCaml equivalent of .c / .h in C.
> Add Ocaml files to the list

- identify/extensions.py
.graphql files are text files describing an interface with a bespoke IDL described in the spec at https://spec.graphql.org/June2018/
> Add extension for .graphql schema

- identify/extensions.py
Add the extension for the GDScript code source files of https://github.com/godotengine/godot
https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_basics.html
GDScript is a language strongly inspired by python.
Godot project has 32.5k :star:  on github.
> Add gd extension for GDScript from Godot

- identify/extensions.py
See #120 
`inx` is an `xml` file used by Incscape and Adobe InDesign
> Add 'inx'->'xml' to 'extensions.py'

- identify/extensions.py
SVG is an XML-based vector image format (cf. [wikipedia](https://en.wikipedia.org/wiki/Scalable_Vector_Graphics))
I hope it is okay that I skipped making an issue before opening this PR.
> Add 'xml' type to 'svg' extension

- identify/extensions.py
Per https://jsonnet.org/learning/tutorial.html:
"Files designed for import by convention end with .libsonnet"
> Add libsonnet extension as jsonnet

- identify/interpreters.py
the lest known might be: https://linux.die.net/man/1/expect
This is needed downstream to better catching supported vs non-supported shells for  `shellcheck` : see https://github.com/cachix/pre-commit-hooks.nix/pull/63#issuecomment-687236558
I didn't bother adding corresponding file extensions, since:
- I don't know them for sure
- The vast majority of cases will probably be covered by this
- If there is need & knowledge, I suggest to add them individually
> add: interpreters

- identify/identify.py
- tests/identify_test.py
nix-shell uses the second line to pass relevant arguments
to the interpreter. Linux (unlike BSD) 
-- see: https://unix.stackexchange.com/a/63981 --
only passes a single argument to the shebang command
(in this case env or nix-shell).
On the second line, if specified, the interpreter is passed
to nix-shell via the -i flag, so we parse this interpreter
if the second line is specified. If not (nix-shell called w/o
arguments) the implicit interpreter is bash.
-- see also: #127 --
closes #128 
@roberth & @zimbatm might I ask you for a quick review to ensure this implementation is 100% correct? Note: we might need to make sure `nix-shell` cmd is preserved (as a wrapper cmd for this use case) on `nix` 2.0
---
See also the nix manual https://nixos.org/manual/nix/stable/#use-as-a-interpreter
--- …
> imp: add nix-shell interpreter parser

- identify/extensions.py
`txsprofile` is an `ini` file used by TeXstudio
> Add 'txsprofile'->'ini' to 'extensions.py'

- README.md
Saves new users like me who were too lazy to read the README in full from having to hunt down that there's a module within the package that needed importing.
> Make the first README example slightly more self-contained

- identify/extensions.py
Adds support for `PKGBUILD` and `*.install` files. Both are interpreted as bash by the Arch Linux packaging toolchain (`makepkg` and `pacman`) but do not use shebangs or common bash file extensions.
Reference: https://www.archlinux.org/pacman/PKGBUILD.5.html
> Adds support for Arch Linux packaging description files

- identify/extensions.py
Closes #162 . Adds markedly structured test as a supported extension (myst).
> Add .myst files to extensions.py

- identify/extensions.py
The '.rake' extension is used to break large Rakefiles into smaller
files. Rakefiles are Ruby files.
https://ruby.github.io/rake/doc/rakefile_rdoc.html#label-Multiple+Rake+Files
> Multiple Rake Files
>
> Not all tasks need to be included in a single Rakefile. Additional
> rake files (with the file extension “.rake”) may be placed in rakelib
> directory located at the top level of a project (i.e. the same
> directory that contains the main Rakefile).
>
> Also, rails projects may include additional rake files in the
> lib/tasks directory.
> Add '.rake' extension as a Ruby file

- identify/extensions.py
These two config files are very common for C++ commit hooks and are yaml formats. It would be great if they were properly support so hooks like check-yaml would recognize them.
> Add support for .clang-tidy and .clang-format

- identify/identify.py
- tests/identify_test.py
Per the (lengthy) discussion in #157 , implements the proposed global constants to classify tags by type, making the code and tests slightly simpler and more robust, and enabling external tools consuming them to differentiate between tag types without resorting to hardcoding.
Also adds a test that all tags from each group are included in the list of all tags, and expands the existing basic tags test to at least one tag from each group.
I'm happy to change the names chosen for the constants if the currently selected ones are problematic, just let me know, thanks!
Resolves #157
> Add global constants to classify tags by type

- identify/identify.py
linter in Python 2.7 is failing because how it uses frozenset
```
File "/home/circleci/project/venv/lib/python2.7/site-packages/identify/identify.py", line 31
ALL_TAGS = {*TYPE_TAGS, *MODE_TAGS, *ENCODING_TAGS}
^
SyntaxError: invalid syntax
```
> Fix frozenset usage, not compatible with Python2.7

- README.md
- identify/identify.py
- tests/identify_test.py
> Identify sockets

- identify/extensions.py
In the [PR to add pre-commit support for dotnet-format](https://github.com/dotnet/format/pull/872#issuecomment-767067745), the maintainers asked for VB support too.
> Add vb to EXTENSIONS

- identify/extensions.py
- tests/identify_test.py
To avoid it being treated as ruby code (e.g. via pre-commit running tools like rubocop).
---
I'm not super confident about this as I don't work much in ruby, but my understanding of `Gemfile.lock` is that it's its own format and not ruby code (vs, for example, `Gemfile`). I started looking at `identify` because my pre-commit config is running rubocop on `Gemfile.lock` and blowing up.
I confirmed with `identify-cli` that this removes the ruby tag.
I'm guessing that somehow the content-based detection is treating my `Gemfile.lock` as ruby? I don't know what the explanation could be other than that.
If I'm wrong about how to handle this, please educate me! 😄
> List Gemfile.lock as type 'text'

- identify/identify.py
- setup.cfg
editdistance appears to be abandoned, I've made [a fork](https://github.com/asottile/editdistance-s) (though I pushed it incorrectly so the repositories aren't linked, oops) which builds abi3 wheels which _should_ improve the portability of `identify[license]`
> use editdistance-s instead of editdistance

- identify/extensions.py
I have a few binary test vectors that pre-commit wants to mess up, calling those .bin seems like pretty solid solution. 
Also, .exe exists, .dll is a very close cousin
> Add .dll as a binary file

- identify/extensions.py
bats is a TAP-compliant testing framework [1]. However, .bats file are bash and shellcheck compatible.
Recognising this files as bash will help them to test with shellcheck
https://github.com/bats-core/
> bats file extension added

- identify/extensions.py
With this change, powershell `.ps1` extensions are identified as:
```
$ identify-cli.exe .\download_cats.ps1
["executable", "file", "powershell", "text"]
```
> Add powershell .ps1 extension

- identify/extensions.py
- add `hcl` extension support
- this is used by most Hashicorp tools, including `consul`, `packer`, and `vault` to name a few
- <https://github.com/hashicorp/hcl>
- alphabetize `EXTENSIONS` keys
- they were mostly there already, but a few weren't quite right
> add hcl extension support

- identify/extensions.py
`.prisma` files (usally `schema.prisma`) are used for defining schema in [prisma](https://www.prisma.io/). Adding this extension would be useful for formatting the schema files using prettier with prisma plugin.
> Add prisma extension

- identify/extensions.py
This adds RELAX NG schema files (https://relaxng.org/) to the extensions file, under the type `relax-ng`, but they're also `xml` files (and hence `text` files).
I don't know much about how commonly this is used or if .rng is used for any other types of files (I have just one such schema in one of my personal projects), but I did a quick Google search and it seems like the other major file type that uses the .rng extension is Nokia phone ringtones, which I'm guessing won't be an issue in practice for projects that use pre-commit.
> Add RELAX NG (.rng) to extensions

- identify/extensions.py
`.vtl` is used for [velocity](https://velocity.apache.org/) templates. vtl templates are used for aws [appsync resolvers](https://docs.aws.amazon.com/appsync/latest/devguide/resolver-mapping-template-reference-programming-guide.html#aws-appsync-resolver-mapping-template-reference-programming-guide).
> Add vtl extension

- identify/extensions.py
adding the `.geojson` file extension, which is basically just a regular `json` file, simply adding standardized field names and geospatial information in a specific order inside array.  being able to check it with `check-json`would be nice.
- more info: https://geojson.org/
- the rfc: https://datatracker.ietf.org/doc/html/rfc7946
<details>
<summary>example file</summary>
```json
{
"type": "FeatureCollection",
"features": [
{
"type": "Feature",
"properties": {},
"geometry": {
"type": "Polygon",
"coordinates": [
[
[
-112.763671875,
41.77131167976407
],
[
-111.4453125,
35.817813158696616
],
[
-103.095703125,
33.7243396617476
],
[
-95.97656249999999,
40.3130432088809
],
[
-106.435546875,
44.902577996288876
],
[
-112.763671875,
41.77131167976407
]
]
]
}
},
{
"type": "Feature",
"properties": …
```
> add geojson extension

- identify/extensions.py
I discovered this extension was missing when I tried to use it with my pre-commit script.
[AspectJ](https://www.eclipse.org/aspectj/) can be used in two ways:
1. Using normal `.java` classes with annotations
2. Using the `.aj` extension with its own syntax
This pull-request adds support for the latter.
> Add support for aspectj file extension.

- identify/extensions.py
go.mod and go.sum are used to define module dependencies and checksums in golang.
adding these two files to the list of known extensions/files.
﻿Signed-off-by: Frederick F. Kautz IV <fkautz@alumni.cmu.edu>
> go.mod and go.sum are now detected as golang

- identify/identify.py
- setup.cfg
resolves #251
(using `https://git.launchpad.net/lpcraft`)
```console
$ time setup-cfg-fmt setup.cfg 
real	0m5.625s
user	0m5.612s
sys	0m0.012s
```
```console
$ time setup-cfg-fmt setup.cfg 
real	0m0.096s
user	0m0.088s
sys	0m0.008s
```
> use ukkonen cutoff on edit distance to improve performance

- identify/extensions.py
From https://prettier.io/docs/en/ignore.html#ignoring-files-prettierignore:
> .prettierignore uses gitignore syntax.
> Add .prettierignore extension

- identify/extensions.py
`.mjs` is the extension recommended for JavaScript modules by the V8 docs: https://v8.dev/features/modules#mjs , and the extension is used by other tools like Babel.
> Add mjs as JavaScript file extension

- identify/extensions.py
`.ino` is the extension used for [Arduino ](https://github.com/arduino/) Language [sketches](https://en.wikipedia.org/wiki/Arduino#Sketch).
The arduino language is a c++ variant, so it is useful to have the ability to utilise c++ formatters / linters.
> Add ino as a c++ file extension

- identify/extensions.py
`.cr` extension is the [crystal lang] extension
Co-authored-by: Anthony Sottile <asottile@umich.edu>
[crystal lang]: https://crystal-lang.org/reference/1.3/using_the_compiler/index.html#creating-an-executable
> add crystal extension

- .pre-commit-config.yaml
- azure-pipelines.yml
- bin/vendor-licenses
- identify/cli.py
- identify/extensions.py
- identify/identify.py
- identify/interpreters.py
- identify/vendor/licenses.py
- setup.cfg
- setup.py
- tests/cli_test.py
- tests/extensions_test.py
- tests/identify_test.py
- tox.ini
python 3.6 reached end of life on 2021-12-23
Committed via https://github.com/asottile/all-repos
> drop python3.6 support

- identify/extensions.py
I was doubting to add a secondary entry `tex`, but I don't think this is justified. Some searching gave me also some non-TeX usage. 
Reference for usage with TeX: https://www.overleaf.com/learn/latex/Understanding_packages_and_class_files
> Adding `sty` files (normally TeX files)

- identify/extensions.py
This PR adds `.inl` as a c++ file extension.
> Add `.inl` extension

- identify/extensions.py
[Liquid](https://github.com/Shopify/liquid) is used by Shopify, Jekyll, and a few other projects in the Ruby ecosystem. The `.liquid` extension isn’t mandatory but it’s very common (see for example [Shopify themes](https://shopify.dev/themes/architecture#directory-structure-and-component-types), where `.liquid` is mandated).
> Add `.liquid` extension for Liquid templates

- identify/extensions.py
[Handlebars](https://handlebarsjs.com/) templates most commonly use the `.hbs` extension. I believe [Ember](https://guides.emberjs.com/release/components/) is the most popular tool that uses `.hbs`. [Eleventy](https://www.11ty.dev/docs/languages/handlebars/) is another example.
> Add `.hbs` extension for Handlebars templates

- identify/extensions.py
Nunjucks is a popular template engine in the Node world, for example with static site generators like [Eleventy](https://www.11ty.dev/docs/languages/nunjucks/). `.njk` is the most common extension for Nunjucks templates, and is [mentioned in the official documentation](https://mozilla.github.io/nunjucks/templating.html#file-extensions).
> Add `.njk` extension for Nunjucks templates

- identify/extensions.py
CJS is (was?) used for CommonJS modules in Node. It's not recommended now (https://github.com/nodejs/modules/issues/293) but Node docs mention it (https://nodejs.org/docs/latest/api/modules.html#file-modules), so presumably some code out there uses it. Also Standard JS' pre-commit hook definition applies to such files with `files` rather than `type` (due to lack of identify support): https://github.com/standard/standard/blob/master/.pre-commit-hooks.yaml .
> Add cjs as a JavaScript file extension

- identify/extensions.py
I noticed that the lock files from poetry and yarn aren't in here yet. Poetry uses toml. Yarn is another story. Yarn v1 files aren't valid yaml files while Yarn v2 lock files are. I think it's better to go just with a text file here.
> add poetry.lock as toml

- identify/extensions.py
I came across this format recently. It's supported by Renovate as one of its possible configs.
The [official implementation](https://github.com/json5/json5) has gone a little quiet (no activity for a year), but I'm not sure that means there's a problem. Even if it did, the format and libraries for it are out there and being used.
There's no new test for this, since it's just a data change.
> Add json5 to extensions

- identify/extensions.py
The Qt project provides a language called qml that is provided in .qml files. This language is common enough that it should be identifiable via tags in order to allow pre-commit and other projects to write hooks for those files.
> support identifying qml files as qml language

- identify/extensions.py
This PR adds FITS (https://fits.gsfc.nasa.gov/) files to the extension list.
> Add FITS files to extension list

- identify/extensions.py
Adding env file extension means, env file validators can run on pre-commit. While it's a bad practice to send .env files to git repo, examples or encrypted templates are very useful.
> Added env/dotenv file extension

- identify/extensions.py
Cylc is a workflow tool and they have recently moved to use
the `.cylc` file extension as their standard to ensure it is unique.
See documentation for this file format in [the Cylc documentation](https://cylc.github.io/cylc-doc/latest/html/tutorial/scheduling/graphing.html).
> Add Cylc configs file extension

- identify/extensions.py
See [Julia getting started instructions](https://docs.julialang.org/en/v1/manual/getting-started/) and/or [their github repo](https://github.com/JuliaLang/julia/tree/master/base) for evidence that `.jl` is the standard file extension for Julia.
> Add julie file extension - 'jl'

- identify/extensions.py
.NET uses *.resx* files to container XML resource descriptors for various resources (e.g. localisation strings, and images) and the IDE manages autogeneration of the XML to describe the contents.
Since it's usually autogenerated, it would be useful to be able to easily target these for exclusion with pre-commit.
I don't know what you consider a canonical source regarding file formats, seeing as anyone can use any format for whatever they choose, but this extension's definition is [generally](https://learn.microsoft.com/en-us/dotnet/core/extensions/work-with-resx-files-programmatically) [well](https://en.wikipedia.org/wiki/List_of_file_formats#Source_code_for_computer_programs) [documented](https://fileinfo.com/extension/resx) [online](https://www.ibm.com/docs/en/cognos-analytics/11.1.0?top …
> Add .resx to extensions.py

- identify/extensions.py
This PR adds .cue to extensions.py. 
This extension is used by the cue-lang project: https://github.com/cue-lang/cue, which is a data language.
> Add .cue to extensions.py

- identify/extensions.py
> Add ppm file to extensions

- identify/extensions.py
This would enable switching out files for types in the [checkmake hook][1].
[1]: https://github.com/mrtazz/checkmake/commit/4e37f3a6ea00208b3f5bd04eaa0f075068237f18
> Adds .make to extensions

- identify/extensions.py
.pug is an extension used by the template engine [Pug](https://github.com/pugjs/pug).
> Add .pug to extensions.py

- identify/extensions.py
This adds `.dbc` files also known as CAN database files to the the supported file extensions. See https://docs.fileformat.com/database/dbc/ as a reference.
> Add file type support for CAN database files (.dbc)

- identify/extensions.py
This will allow e.g. https://github.com/pre-commit/mirrors-clang-format to format https://protobuf.dev/reference/protobuf/textformat-spec/ files together with https://github.com/pre-commit/mirrors-clang-format/pull/22.
> Add *.textproto support

- identify/extensions.py
Suggest adding the "JSON" type to Jupyter notebooks  (`.ipynb` files), as notebooks are JSON files.
> Add "json" type to jupter notebooks

- identify/extensions.py
Adds the canonical extension for text-serialized protocol buffers. ([source](https://protobuf.dev/reference/protobuf/textformat-spec/#text-format-files))
> Add txtpb extension.

- identify/extensions.py
Add `copy.bara.sky` which is the default config file of [copybara](https://github.com/google/copybara). It is a starlark file like `.bzl`.
Not adding `.sky` extension as I did not see any other starlark file use `.sky` as extension.
> Support identifying copy.bara.sky

- identify/extensions.py
`.ggb` file extensions are used for [GeoGebra](https://www.geogebra.org/?lang=en) drawings. 
Web research did not result in any ambiguity, but pointed straight to this usecase (https://fileinfo.com/extension/ggb).
I also ran a `file my_file.ggb` which resulted in `Zip archive data, at least v2.0 to extract`
> Add GGB file extension

- identify/extensions.py
I was honestly surprised that `urdf` was [already supported](https://github.com/pre-commit/identify/pull/210), but I'm taking it further and adding [`xacro`](https://github.com/ros/xacro)
> Add xacro extension

- identify/extensions.py
- tests/identify_test.py
* "The syntax of Vagrantfiles is Ruby" ref. https://developer.hashicorp.com/vagrant/docs/vagrantfile
> feat: identify `Vagrantfile` as Ruby

- identify/extensions.py
- tests/identify_test.py
* "Salt-lint supports local configuration via a .salt-lint configuration file" ref.
https://github.com/warpnet/salt-lint/blob/main/docs/index.md#configuration-file
> feat: identify `.salt-lint` as YAML

- identify/extensions.py
> Schema files use the extension ".avsc", while encoded files (of any sort) use the extension ".avro"
http://fileformats.archiveteam.org/wiki/Avro
> feat: identify `.avsc` as Avro schema

- identify/extensions.py
`pyt` is the extension for the [Esri Python Toolbox](https://pro.arcgis.com/en/pro-app/latest/arcpy/geoprocessing_and_python/a-quick-tour-of-python-toolboxes.htm) file format, written in plain text Python.
> Add `pyt` extension

- identify/extensions.py
Metal Programming guide: Metal Tools
> ## File Extension for Metal Shading Language Source Files
>
> For Metal shading language source code file names, you must use the
> .metal file name extension to ensure that the development tools
> (Xcode and the GPU frame debugger) recognize the source files when
> debugging or profiling.
> feat: Indentify `metal` as Metal Shading Language

- identify/extensions.py
Introduce dedicated types for Cargo.toml and Cargo.lock files. These are similar to go.mod and go.sum files.
> Identify Cargo.toml and Cargo.lock as cargo and cargo-lock

- identify/extensions.py
`ejson` is a pretty popular "encrypted json" format and open source tool built by Shopify. `ejson` files are just JSON files where terminal string nodes are encrypted.
[More info](https://github.com/Shopify/ejson)
> Add ejson extension

- identify/extensions.py
Add identification of archives in the [bzip3 format](https://github.com/kspalaiologos/bzip3).
> feat: identify bz3 files as bzip3 archives

- identify/extensions.py
- tests/identify_test.py
Add Tiltfile ~~+ Starlark~~ support. Tiltfiles are written in Starlark, which is a language intended for use as a configuration language. It was originally designed for the [Bazel](https://bazel.build/) build system. Starlark is a dialect of **Python**.
~~background: Lots of Python targeting pre-commit hooks (like ruff) can also be applied to Starlark files. This PR enables to apply those hooks via specifying `types_or: [starlark]` or  `types_or: [tiltfile]` or `types_or: [bazel]` depending on what is needed. Not every Python pre-commit hook applies to every Starlark file, as there are different variants with some [language features](https://pkg.go.dev/go.starlark.net/resolve?utm_source=godoc#pkg-variables) enabled or disabled.~~
refs:
* https://docs.tilt.dev/api
* …
> Add Tiltfile

- identify/extensions.py
`.psm1` are PowerShell module files, `.psd1` are PowerShell data files (https://learn.microsoft.com/en-us/powershell/scripting/developer/module/understanding-a-windows-powershell-module?view=powershell-7.4).
> feat: identify .psm1 and .psd1 files as powershell

- identify/extensions.py
Adds `.templ` as an extension as per https://templ.guide/core-concepts/template-generation
> feat: add `templ` to extensions.py

- identify/interpreters.py
add [uv](https://github.com/astral-sh/uv) to the interpreters list
> add uv to interpreters list

- identify/interpreters.py
Reverts pre-commit/identify#503
resolves #512
> Revert "add uv to interpreters list"

- identify/extensions.py
Arch Linux/ALPM PKGBUILDs are not currently being identified as `shell` files, but they’re really just specialised bash scripts, and thus also `shell` files.
This makes `PKGBUILD` files a superset of the `bash` extension, which both makes it inherit the `shell` type, and also ensures that it will automatically adopt any future changes/additions that might be made to the `bash` extension.
> fix: make PKGBUILD files a superset of .bash

- identify/extensions.py
Piskel is a browser-based sprite editor. Its file format is JSON-based (though the JSON contains base64-encoded PNG data).
Recognise the .piskel extension and identify it analogously to .svg: it is text, image, json and piskel.
https://github.com/piskelapp/piskel
http://justsolve.archiveteam.org/wiki/Piskel_canvas
> Add .piskel extension
