pre-commit/identify

identify/extensions.py, identify/identify.py, tests/extensions_test.py, tests/identify_test.py
The list is pretty for small now, I'll probably do something like try to classify all the files from the top 100 github repos or something to improve it later on.
=> Implement tags_from_filename

identify/identify.py
I want to expose this such that pre-commit could _warn_ or _error_ on unknown tags.
=> Expose ALL_TAGS

identify/identify.py, tests/identify_test.py
=> Include basic tags in ALL_TAGS

.pre-commit-config.yaml, .travis.yml, tox.ini
=> Split the travis tox environments

identify/extensions.py
=> jshintrc is json

identify/identify.py
I keep thinking about this but also keep forgetting to try it, let's see what travis says :)
=> Use rpartion instead of if + split

identify/identify.py, tests/identify_test.py
=> Name matches also go through extension lookup

identify/identify.py, tests/identify_test.py
=> Fix crash with shebangs containing quotes

identify/extensions.py
See https://gyp.gsrc.io/docs/LanguageSpecification.md
=> Add extensions for `gyp`

identify/extensions.py
I'm not sure what the scope of this project is but, if it's useful, here's the extension for the frontend language PureScript (http://purescript.org).
=> Added PureScript extension (.purs)

identify/extensions.py
https://github.com/facebookarchive/mention-bot
=> Add extension for mention-bot

identify/extensions.py
=> Add plantuml extension

identify/extensions.py
See here: https://github.com/pypa/pipfile
=> Know that Pipfile is a TOML file

identify/extensions.py
Jsonnet is a JSON templating language;
http://jsonnet.org
=> add jsonnet file extension

identify/extensions.py
=> Add both Dart and Zig file detection

identify/extensions.py
Nix is a language and build system. See https://nixos.org/nix/
=> Add nix file type

identify/extensions.py
=> Plantuml; .puml suffix

identify/extensions.py
=> fix: add 'image' tag for SVG files

.pre-commit-config.yaml, .travis.yml, tox.ini
Committed via https://github.com/asottile/all-repos
=> Run pre-commit autoupdate

identify/extensions.py
=> added ipynb extension

identify/extensions.py
=> Add mdx extension

identify/extensions.py
=> Add detection for binary pyz files

identify/extensions.py
Add `.sass` files to recognize them from extensions.
=> Add 'sass' files extension

identify/extensions.py
Lean is https://leanprover-community.github.io/, an
interactive theorem prover / programming language.
=> Add support for Lean.

identify/extensions.py
Add `.webp` files to recognize them from extensions.
=> Add 'webp' file extension

identify/extensions.py
> Twig is a modern template engine for PHP
https://twig.symfony.com/
=> Add .twig extension

identify/extensions.py
Add `.avif` extension to recognize files from extensions.
=> Add `avif` file extension

.pre-commit-config.yaml, bin/vendor-licenses, identify/cli.py, identify/extensions.py, identify/identify.py, identify/interpreters.py, identify/vendor/licenses.py, setup.cfg, setup.py, tests/cli_test.py, tests/extensions_test.py, tests/identify_test.py, tox.ini
see also [python 3 statement](https://github.com/asottile/scratch/wiki/python-3-statement)
=> drop python 2

identify/identify.py, tests/identify_test.py
resolves pre-commit/pre-commit#1830
=> fix parse_shebang_from_file for windows store python

identify/extensions.py
`.hh` is also a common suffix for C++ header files. Please consider pulling.
=> identify c++ header files with .hh suffix

identify/extensions.py
Hi @asottile and collaborators! I would like to add support for CUDA header files, which often have the extension `.cuh`. This [StackOverflow post](https://stackoverflow.com/a/2393855) can be used as supporting evidence. Thank you, pre-commit is a wonderful tool.
=> Detect .cuh as CUDA header file.

identify/extensions.py
Adds support for the URDF file format which is a type of XML file.
=> Add URDF identification

identify/extensions.py
Detect the waf build system's wscript files as Python.
https://waf.io/
=> Detect waf wscript files as Python

identify/extensions.py
These are script files for the Kotlin language:
https://kotlinlang.org/docs/command-line.html#run-scripts
=> Add the '.kts' extension for kotlin

identify/identify.py, tests/identify_test.py
=> Handle shebangs with multiple arguments via env -S

identify/extensions.py
https://github.com/sveltejs/svelte
=> add .svelte extension

identify/extensions.py
=> .m files don't get associated with C language

identify/extensions.py
m4 is a simple language for creating macros
https://en.wikipedia.org/wiki/M4_(computer_language)
=> Add m4 macro language file extension support

identify/extensions.py
Mustache is a templating language: https://mustache.github.io/
=> Add .mustache file type

identify/extensions.py
support [beancount](https://beancount.github.io/docs/index.html) files
=> Add *.beancount support

identify/interpreters.py, tests/identify_test.py
=> Add php to interpreters list

identify/extensions.py
Documentation for .ansible-lint [1].
[1] https://ansible-lint.readthedocs.io/configuring/
=> Add yaml extension for .ansible-lint config file

identify/extensions.py
For reference: https://github.com/pre-commit/identify/issues/432
While adding the new file type, I noticed some entries are not properly sorted, I've fixed it in a separate commit in case it's an unwanted change.
=> Add xctestplan file type

identify/extensions.py
Add identification of files written in the [Gleam programming language](https://en.wikipedia.org/wiki/Gleam_(programming_language))
=> feat: identify gleam files

identify/extensions.py
According to Wikipedia [1] .asm is a known extension for assembler files.
[1] https://en.wikipedia.org/wiki/Assembly_language
=> Add '.asm' file extension as 'asm' filetype

identify/extensions.py
Would like to write some pre-commit hooks for [https://www.sas.com] programs and macros.
=> feat: Register sas as an extension

identify/extensions.py
According to [1] WSDL is an XML format.
[1] https://www.w3.org/TR/wsdl.html
=> extensions: Introduce wsdl

identify/extensions.py
Documented as `ini` here: https://github.com/sqlfluff/sqlfluff/blob/5d5fe0a6d3fca6c49c36c3d35af6952984f0bb8f/docs/source/configuration/setting_configuration.rst#L29-L33
=> Add support for `.sqlfluff`
